<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: Arial, sans-serif; font-size: 10pt; color: #1a1a1a; }
.stripe-red   { background: #e31c23; height: 6px; }
.stripe-black { background: #1a1a1a; height: 3px; margin-top: 2px; }
.header { padding: 12px 20px; display: flex; justify-content: space-between; align-items: flex-start; }
.company-name { font-size: 15pt; font-weight: 900; color: #e31c23; }
.title { font-size: 16pt; font-weight: 900; }
.period { font-size: 9pt; color: #666; margin-top: 3px; }
.summary { display: flex; gap: 12px; padding: 10px 20px; }
.summary-card { flex: 1; border: 1px solid #e5e7eb; border-radius: 6px; padding: 8px 12px; }
.summary-card .label { font-size: 8pt; color: #666; text-transform: uppercase; }
.summary-card .value { font-size: 13pt; font-weight: 700; margin-top: 2px; }
.red { color: #e31c23; }
.green { color: #16a34a; }
.orange { color: #ea580c; }
table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 9pt; }
thead tr { background: #e31c23; color: #fff; }
th { padding: 6px 10px; text-align: left; font-weight: bold; }
th.r, td.r { text-align: right; }
tbody tr:nth-child(even) { background: #f9fafb; }
td { padding: 5px 10px; border-bottom: 1px solid #f0f0f0; }
tfoot tr { background: #f3f4f6; font-weight: bold; border-top: 2px solid #d1d5db; }
.section { padding: 0 20px; }
.footer-r { background: #e31c23; height: 5px; margin-top: 20px; }
.footer-b { background: #1a1a1a; color: #fff; text-align: center; padding: 6px; font-size: 8pt; }
</style>
</head>
<body>

<div class="stripe-red"></div>
<div class="stripe-black"></div>

<div class="header">
    <div>
        <div class="company-name">JAAN Network</div>
        <div style="font-size:8pt;color:#666">{{ $settings['company_address'] ?? '' }}</div>
    </div>
    <div style="text-align:right">
        <div class="title">DAILY CASH SUMMARY</div>
        <div class="period">
            @if($dateFrom->toDateString() === $dateTo->toDateString())
                {{ $dateFrom->format('d M Y') }}
            @else
                {{ $dateFrom->format('d M Y') }} &ndash; {{ $dateTo->format('d M Y') }}
            @endif
        </div>
    </div>
</div>

<div class="summary">
    <div class="summary-card">
        <div class="label">Total Invoices</div>
        <div class="value">{{ $count }}</div>
    </div>
    <div class="summary-card">
        <div class="label">Total Revenue</div>
        <div class="value red">LKR {{ number_format($totalAmount) }}</div>
    </div>
    <div class="summary-card">
        <div class="label">Collected</div>
        <div class="value green">LKR {{ number_format($totalPaid) }}</div>
    </div>
    <div class="summary-card">
        <div class="label">Outstanding</div>
        <div class="value orange">LKR {{ number_format($outstanding) }}</div>
    </div>
</div>

<div class="section">
    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Date</th>
                <th>Customer</th>
                <th class="r">Amount (LKR)</th>
                <th class="r">Paid (LKR)</th>
                <th class="r">Balance (LKR)</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($invoices as $inv)
            <tr>
                <td>{{ $inv->invoice_number }}</td>
                <td>{{ $inv->invoice_date->format('d/m/Y') }}</td>
                <td>{{ $inv->customer_name }}</td>
                <td class="r">{{ number_format($inv->total_amount) }}</td>
                <td class="r">{{ number_format($inv->paid_amount) }}</td>
                <td class="r">{{ number_format($inv->balance) }}</td>
                <td>{{ ucfirst($inv->payment_status) }}</td>
            </tr>
            @empty
            <tr><td colspan="7" style="text-align:center;padding:20px;color:#999">No invoices for this period.</td></tr>
            @endforelse
        </tbody>
        @if($invoices->count())
        <tfoot>
            <tr>
                <td colspan="3" style="padding:6px 10px">Total</td>
                <td class="r" style="padding:6px 10px">{{ number_format($totalAmount) }}</td>
                <td class="r" style="padding:6px 10px;color:#16a34a">{{ number_format($totalPaid) }}</td>
                <td class="r" style="padding:6px 10px;color:#e31c23">{{ number_format($outstanding) }}</td>
                <td></td>
            </tr>
        </tfoot>
        @endif
    </table>
</div>

<div class="footer-r"></div>
<div class="footer-b">Generated by {{ $settings['company_name'] ?? 'JAAN Network (Pvt) Ltd' }} &mdash; {{ now()->format('d M Y, H:i') }}</div>

</body>
</html>
